baseURL = "https://nachiketkanore.github.io/blog/"
languageCode = 'en-us'
title = 'Nachiket Kanore'
theme = "etch"
paginate = 10


enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "My Life Logs"
  copyright = "Copyright © 2023 Nachiket Kanore"
  dark = "auto"
  highlight = true

[menu]
  [[menu.main]]
    identifier = "Posts"
    name = "posts"
    title = "Posts"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "About"
    url = "/about/"
    weight = 20

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allows HTML in Markdown
  unsafe = true
